# Generated by Django 4.1 on 2022-09-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                (
                    'status',
                    models.IntegerField(
                        choices=[
                            ('0', 'Girton Undergraduate'),
                            ('1', 'Girton Postgraduate'),
                            ('2', 'Girton Staff'),
                            ('3', 'Girton Alumnus/a'),
                        ]
                    ),
                ),
                (
                    'auth_type',
                    models.IntegerField(
                        choices=[('0', 'Raven'), ('1', 'Manual')], default='0'
                    ),
                ),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
