# Generated by Django 4.1 on 2022-09-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="has_paid",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="kind",
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_queue_jump",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Queued"), (1, "Pending payment"), (2, "Confirmed")],
                default=0,
            ),
            preserve_default=False,
        ),
    ]
